name: Barman Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'barman release (ex: 2.18)'
        required: true

jobs:
  set_version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/enterprisedb/pandoc:2.2.1
      credentials:
        username: didiermichel
        password: ${{ secrets.DELIVER_REPO_ACCESS_TOKEN }}
    steps:
      - name: Run only on master
        # To change for master when ready
        if: github.ref_name != 'dev/barman_release'
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check version '${{ github.event.inputs.release }}' is valid and tag does not already exits
        shell: bash
        run: |
          if [[ -z "$(echo ${{ github.event.inputs.release }} | grep -E "^[1-9]\.[0-9]+$")" ]]
          then
             echo "wrong pattern for version"
             exit 1
          fi
          git fetch origin 'refs/tags/*:refs/tags/*'
          tag_search=`git tag -l "release/${{ github.event.inputs.release }}"`
          if [[ "$tag_search" ]]
          then
            echo "tag $tag_search already exist."
            exit 1
          fi
      - name: Update version in barman.
        run: |
          ${GITHUB_WORKSPACE}/scripts/ci-set-version.sh ${{ github.event.inputs.release }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '["barman/version.py", "doc/*"]'
          default_author: github_actions
          message:  "Version set to ${{ github.event.inputs.release }}"
          push: true

  news_tag_release:
    needs: set_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@master
        with:
          repository: EnterpriseDB/barman-deliver.git
          ref: main
          token: ${{ secrets.DELIVER_REPO_ACCESS_TOKEN}}
          # token: ${{ secrets.GITHUBSECURITYTOKEN}}
          path: barman-deliver
      - name: Update repo with new version ${{ github.event.inputs.release }}
        uses: ./barman-deliver
        with:
          command: 'barman'
          release: "release/${{ github.event.inputs.release }}"
          GITHUB_TOKEN: ${{ github.token }}
      - name: Commit News and tag
        uses: EndBug/add-and-commit@v9
        with:
          add: 'NEWS'
          default_author: github_actions
          message: "Update changelog for ${{ env.release_name }}"
          tag: 'release/${{ github.event.inputs.release }} -m "Release ${{ github.event.inputs.release }}"'
      - name: Create draft release from tag
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "release_content.md"
          tag: "release/${{ github.event.inputs.release }}"
          name: "Barman ${{ github.event.inputs.release }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true

  dispatch:
    name: "trigger ${{ matrix.repo }} release"
    needs: news_tag_release
    strategy:
      matrix:
        repo:
          - 'EnterpriseDB/barman-packaging'
          - 'EnterpriseDB/edb-barman-packaging'
          - 'EnterpriseDB/barman.github.io'
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          # Personal access token to trigger the other pipelines should be replace by GITHUBSECURITYTOKEN
          token: ${{ secrets.DELIVER_REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: dispatch_release
          client-payload: '{"release_name": "release/${{ github.event.inputs.release }}"}'
